package com.example.inventario.navigation

object NavRoutes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val RECUPERAR_PASSWORD = "recuperarPassword"
    const val MENU_PRINCIPAL = "menuP"
    const val MENU_BODEGAS = "menuBodegas"
    const val PANEL = "panel"
    const val AUDITORIA_HUB = "auditoriaHub"
    const val CONFIGURACION = "configuracion"
    const val USUARIOS = "usuarios"
    const val CREAR_USUARIO = "crearUsuario"
    const val LOGS = "logs"
    const val NOTIFICACIONES = "notificaciones"
    const val TEMAS = "temas"
    const val PAPELERA = "papelera"
    const val CREAR_BODEGA = "crearBodega"
    const val PERFIL = "perfil"

    fun menuBodega(bodegaId: String) = "menuBodega/$bodegaId"
    fun inventario(bodegaId: String) = "inventario/$bodegaId"
    fun crearProducto(bodegaId: String) = "crearProducto/$bodegaId"
    fun editarProducto(productoId: Int, bodegaId: String) =
        "editarProducto/$productoId/$bodegaId"
    fun entradas(bodegaId: String) = "entradas/$bodegaId"
    fun crearEntrada(bodegaId: String) = "crearEntrada/$bodegaId"
    fun editarEntrada(entradaId: Int, bodegaId: String) = "editarEntrada/$entradaId/$bodegaId"
    fun salidas(bodegaId: String) = "salidas/$bodegaId"
    fun crearSalida(bodegaId: String) = "crearSalida/$bodegaId"
    fun editarSalida(salidaId: Int, bodegaId: String) = "editarSalida/$salidaId/$bodegaId"
    fun facturas(bodegaId: String) = "facturas/$bodegaId"
    fun crearFactura(bodegaId: String) = "crearFactura/$bodegaId"
    fun editarFactura(facturaId: Int) = "editarFactura/$facturaId"
    fun detalleFactura(facturaId: Int) = "detalleFactura/$facturaId"
    fun crearDetalleFactura(facturaId: Int) = "crearDetalleFactura/$facturaId"
    fun editarDetalleFactura(detalleId: Int) = "editarDetalleFactura/$detalleId"
    fun dashboard(bodegaId: String) = "dashboard/$bodegaId"
    fun panelBodega(bodegaId: String) = "panelBodega/$bodegaId"
    fun stockBajo(bodegaId: String) = "stockBajo/$bodegaId"
    fun existencias(bodegaId: String) = "existencias/$bodegaId"
    fun presupuesto(bodegaId: String) = "presupuesto/$bodegaId"
    fun reportesOperativos(bodegaId: String) = "reportesOperativos/$bodegaId"
    fun auditoria(bodegaId: String) = "auditoria/$bodegaId"
    fun movimientos(bodegaId: String) = "movimientos/$bodegaId"
    fun kardex(bodegaId: String) = "kardex/$bodegaId"
    fun categorias(bodegaId: String) = "categorias/$bodegaId"
    fun vales(bodegaId: String) = "vales/$bodegaId"
    fun crearVale(bodegaId: String) = "crear_vale/$bodegaId"
    fun detalleVale(valeId: Int, bodegaId: String) = "detalle_vale/$valeId/$bodegaId"
    fun traslados(bodegaId: String) = "traslados/$bodegaId"
    fun crearTraslado(bodegaId: String) = "crear_traslado/$bodegaId"
    fun detalleTraslado(trasladoId: Int) = "detalle_traslado/$trasladoId"
    fun editarUsuario(usuarioId: Int) = "editarUsuario/$usuarioId"
    fun editarUsuarioRoute() = "editarUsuario/{usuarioId}"
    fun editarProductoRoute() = "editarProducto/{productoId}/{bodegaId}"
    fun editarEntradaRoute() = "editarEntrada/{entradaId}/{bodegaId}"
    fun editarSalidaRoute() = "editarSalida/{salidaId}/{bodegaId}"
    fun editarFacturaRoute() = "editarFactura/{facturaId}"
    fun crearDetalleFacturaRoute() = "crearDetalleFactura/{facturaId}"
    fun detalleFacturaRoute() = "detalleFactura/{facturaId}"
    fun editarDetalleFacturaRoute() = "editarDetalleFactura/{detalleId}"
    fun detalleValeRoute() = "detalle_vale/{valeId}/{bodegaId}"
    fun configuracionBodega(bodegaId: String) = "configuracion/$bodegaId"
    fun papeleraBodega(bodegaId: String) = "papelera/$bodegaId"
}
